package com.familylocation.mobiletracker.phoneToolsModule;

import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RelativeLayout;

import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;


import java.util.ArrayList;
import java.util.List;

import com.familylocation.mobiletracker.BaseActivity;
import com.familylocation.mobiletracker.MyApplication;
import com.familylocation.mobiletracker.R;


public class ISDCodeActivity extends BaseActivity {

    String[] code = {"+358 18",
            "+93",
            "+355",
            "+213",
            "+1 684",
            "+376",
            "+244",
            "+1 264",
            "+1 268",
            "+54",
            "+374",
            "+297",
            "+247",
            "+61",
            "+672 1",
            "+43",
            "+994",
            "+1 242",
            "+973",
            "+880",
            "+1 246",
            "+375",
            "+32",
            "+501",
            "+229",
            "+1 441",
            "+975",
            "+591",
            "+387",
            "+267",
            "+47",
            "+55",
            "+246",
            "+1 284",
            "+673",
            "+359",
            "+226",
            "+257",
            "+855",
            "+237",
            "+1",
            "+238",
            "+599",
            "+1 345",
            "+236",
            "+235",
            "+56",
            "+86",
            "+61 89164",
            "+61 89162",
            "+57",
            "+269",
            "+682",
            "+506",
            "+385",
            "+53",
            "+599 9",
            "+357",
            "+420",
            "+243",
            "+45",
            "+253",
            "+1 767",
            "+1 809, +1 829, +1 849",
            "+670",
            "+593",
            "+20",
            "+503",
            "+240",
            "+291",
            "+372",
            "+268",
            "+251",
            "+500",
            "+298",
            "+679",
            "+358",
            "+33",
            "+594",
            "+689",
            "+262",
            "+241",
            "+220",
            "+995",
            "+49",
            "+233",
            "+350",
            "+30",
            "+299",
            "+1 473",
            "+590",
            "+1 671",
            "+502",
            "+44 1481, +44 7781, +44 7839, +44 7911",
            "+224",
            "+245",
            "+592",
            "+509",
            "+1 672",
            "+504",
            "+852",
            "+36",
            "+354",
            "+91",
            "+62",
            "+98",
            "+964",
            "+353",
            "+44 1624, +44 7524, +44 7624, +44 7924",
            "+972",
            "+39",
            "+225",
            "+1 876",
            "+81",
            "+44 1534",
            "+962",
            "+7 6, +7 7",
            "+254",
            "+686",
            "+383",
            "+965",
            "+996",
            "+856",
            "+371",
            "+961",
            "+266",
            "+231",
            "+218",
            "+423",
            "+370",
            "+352",
            "+853",
            "+261",
            "+265",
            "+60",
            "+960",
            "+223",
            "+356",
            "+692",
            "+596",
            "+222",
            "+230",
            "+262 269, +262 639",
            "+52",
            "+691",
            "+373",
            "+377",
            "+976",
            "+382",
            "+1 664",
            "+212",
            "+258",
            "+95",
            "+264",
            "+674",
            "+977",
            "+31",
            "+599",
            "+687",
            "+64",
            "+505",
            "+227",
            "+234",
            "+683",
            "+672 3",
            "+850",
            "+389",
            "+44 28",
            "+1 670",
            "+47",
            "+968",
            "+92",
            "+680",
            "+970",
            "+507",
            "+675",
            "+595",
            "+51",
            "+63",
            "+64",
            "+48",
            "+351",
            "+1 787, +1 939",
            "+974",
            "+262",
            "+242",
            "+40",
            "+7",
            "+250",
            "+590",
            "+290",
            "+1 869",
            "+1 758",
            "+590",
            "+508",
            "+1 784",
            "+685",
            "+378",
            "+239",
            "+966",
            "+221",
            "+381",
            "+248",
            "+232",
            "+65",
            "+421",
            "+386",
            "+677",
            "+252",
            "+27",
            "+500",
            "+82",
            "+211",
            "+34",
            "+94",
            "+249",
            "+597",
            "+47 79",
            "+46",
            "+41",
            "+963",
            "+886",
            "+992",
            "+255",
            "+66",
            "+228",
            "+690",
            "+676",
            "+1 868",
            "+216",
            "+90",
            "+993",
            "+1 649",
            "+688",
            "+256",
            "+380",
            "+971",
            "+44",
            "+1",
            "+246",
            "+598",
            "+998",
            "+678",
            "+379",
            "+58",
            "+84",
            "+1 340",
            "+681",
            "+212",
            "+967",
            "+260",
            "+263"};

    String[] coutryName = {"Aland Islands",
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Ascension Island",
            "Australia",
            "Australian Antarctic Territory",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Caribbean Netherlands",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Cook Islands",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czech Republic",
            "Democratic Republic of the Congo",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Falkland Islands (Malvinas)",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "French Southern and Antarctic Lands",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard Island and McDonald Islands",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "North Korea",
            "North Macedonia",
            "Northern Ireland",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Réunion",
            "Republic of the Congo",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Barthélemy",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (French part)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Virgin Islands, U.S.",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"};

    private EditText et_search;
    private List<NumLocatorModel> models = new ArrayList<>();
    private RecyclerView recyclerView;
    private ISDNumberAdapter mAdapter;

    private ImageView btBack;
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_isd_code);
//        getWindow().setFlags(WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS);


        for (int i = 0; i < coutryName.length; i++) {
            NumLocatorModel mModel = new NumLocatorModel(coutryName[i], code[i]);
            models.add(mModel);
        }

//        RelativeLayout rel_banner = findViewById(R.id.rel_banner);
//        loadBannerAds(rel_banner);

        RelativeLayout rl_adplaceholder = findViewById(R.id.rl_adplaceholder);
        MyApplication.getInstance().loadNativeAd(rl_adplaceholder, ISDCodeActivity.this);


        recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setHasFixedSize(true);
        mAdapter=new ISDNumberAdapter(this,models);
        recyclerView.setAdapter(mAdapter);

        et_search = findViewById(R.id.et_search);
        et_search.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                searchFilter(s.toString());
            }

            @Override
            public void afterTextChanged(Editable s) {

            }
        });

        btBack = findViewById(R.id.btBack);
        btBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });
    }

    private void searchFilter(String text) {
        List<NumLocatorModel> temp = new ArrayList();
        for (NumLocatorModel model : models) {
            if (model.getCoutryName().toLowerCase().contains(text)) {
                temp.add(model);
            }
        }
        mAdapter.updateList(temp);
    }

}
